//USEUNIT Helpers
function TC399578_OpenAndCloseCamsInCameosInAllPossibleWays()
{
  TestedApps.OperatorClient.Run();
  Helpers.OperatorClient_WaitForReady();
  let operatorClient = Aliases.OperatorClient;
  //operatorClient.HwndSource_StyleableWindow.StyleableWindow.ButtonOk.ClickButton();
  let monitorForm = operatorClient.Control;
  let containerControl = monitorForm.ContainerControl;
  let windowDockingArea = containerControl.WindowDockingArea;
  let wnd = windowDockingArea.DockableWindow.LogicalTree.LogicalTree.Logical_Tree;
  let wnd2 = wnd.Camera_1_5_;
  wnd2.DblClick();
  let wnd3 = wnd.Camera_2_6_;
  wnd3.DblClick();
  let wnd4 = wnd.Camera_3_7_;
  wnd4.DblClick();
  let wnd5 = wnd.Camera_4_8_;
  wnd5.DblClick();
  let cameoSpacePanel = windowDockingArea.DockableWindow2.CameoSpace.ToggleLiveCameoSpace.CameoSpacePanel;
  let cameo1 = cameoSpacePanel.Cameo1;
  let cameo2 = cameoSpacePanel.Cameo2;
  let cameo3 = cameoSpacePanel.Cameo3;
  let cameo4 = cameoSpacePanel.Cameo4;
  //cameo.Click(235, 9);
  cameo1.Close();
  cameo2.Close();
  //cameo2.Click(231, 9);
  cameo3.Close();
  //cameo3.Click(234, 8);
  cameo4.Close();
  //cameo4.Click(232, 10);
  cameo1.Click();
  wnd2.ClickR();
  let popupMenuControlTrusted = operatorClient.DropDownForm.PopupControl;
  wnd = popupMenuControlTrusted.MenuAgent;
  let wnd6 = wnd.Show;
  wnd6.Click();
  let wnd7 = popupMenuControlTrusted.Show.in_selected_image_pane;
  wnd7.Click();
  cameo2.Click();
  wnd3.ClickR();
  wnd6.Click();
  wnd7.Click();
  cameo3.Click();
  wnd4.ClickR();
  wnd6.Click();
  wnd7.Click();
  cameo4.Click();
  wnd5.ClickR();
  wnd6.Click();
  wnd7.Click();
  cameo1.ClickR();
  wnd6 = wnd.Close_image_pane;
  wnd6.Click();
  cameo2.ClickR();
  wnd6.Click();
  cameo3.ClickR();
  wnd6.Click();
  cameo4.ClickR();
  wnd6.Click();
  Helpers.DragAndDrop(wnd2, cameo1);
  Helpers.DragAndDrop(wnd3, cameo2);
  Helpers.DragAndDrop(wnd4, cameo3);
  Helpers.DragAndDrop(wnd5, cameo4);
//  wnd2.Drag(79, 14, 641, 79);
//  wnd3.Drag(75, 12, 899, 50);
//  wnd4.Drag(68, 15, 1143, 10);
//  wnd5.Drag(69, 12, 1372, 3);
  cameo1.Click();
  wnd = containerControl.UltraToolbarsDockArea.Toolbar2.Image_pane;
  wnd.Click();
  wnd2 = popupMenuControlTrusted.Image_pane.Close;
  wnd2.Click();
  cameo2.Click();
  wnd.Click();
  wnd2.Click();
  cameo3.Click();
  wnd.Click();
  wnd2.Click();
  cameo4.Click();
  wnd.Click();
  wnd2.Click();
  //monitorForm.Button.ClickButton();
  //operatorClient.BoschMessageBox.ContainerControl.buttonMiddle.ClickButton();
  Helpers.OperatorClient_RestoreDefaultSettings();
  Helpers.OperatorClient_Close();
}